'use client';

import { useEffect, useMemo, useState } from 'react';
import { Search, Plus, SlidersHorizontal, MoreHorizontal, ChevronRight, Activity, ShieldAlert, Database, FileText, Crosshair, RotateCcw, Send, Download, X, CheckCircle2 } from 'lucide-react';
import { store } from '@/lib/store';
import { useAuth } from '@/lib/auth-context';
import type { CaseDetail, Evidence, AttributionHypothesis } from '@/lib/types';

const riskClass: Record<string, string> = {
  critical: 'text-red-400 bg-red-950/30 border-red-900/60',
  high: 'text-orange-400 bg-orange-950/30 border-orange-900/60',
  medium: 'text-amber-400 bg-amber-950/30 border-amber-900/60',
  low: 'text-slate-400 bg-slate-800/50 border-slate-700/60',
  cleared: 'text-teal-400 bg-teal-950/30 border-teal-900/60',
};

const statusClass: Record<string, string> = {
  open: 'text-teal-400', under_review: 'text-amber-400', pending_approval: 'text-orange-400', approved: 'text-slate-300', archived: 'text-slate-600',
};

export function CaseListView() {
  const [view, setView] = useState<'list' | 'create' | 'detail' | 'evidence' | 'vasp' | 'audit' | 'report' | 'sahyog'>('list');
  const [selectedCase, setSelectedCase] = useState<CaseDetail | null>(null);
  const [query, setQuery] = useState('');
  const [riskFilter, setRiskFilter] = useState('all');
  const { user } = useAuth();

  useEffect(() => {
    const handleNavigate = (event: Event) => {
      const nextView = (event as CustomEvent<typeof view>).detail;
      setView(nextView);
      if (!selectedCase && nextView !== 'list' && nextView !== 'create') {
        setSelectedCase(store.getCases()[0] || null);
      }
    };
    window.addEventListener('vault-x:navigate', handleNavigate);
    return () => window.removeEventListener('vault-x:navigate', handleNavigate);
  }, [selectedCase]);

  const cases = useMemo(() => store.getCases().filter((item) => {
    const matchesQuery = `${item.number} ${item.title} ${item.chain}`.toLowerCase().includes(query.toLowerCase());
    const matchesRisk = riskFilter === 'all' || item.riskLevel === riskFilter;
    return matchesQuery && matchesRisk;
  }), [query, riskFilter]);

  const openCase = (item: CaseDetail) => { setSelectedCase(item); setView('detail'); };

  return (
    <main className="min-h-[calc(100vh-56px)] p-5 lg:p-7 bg-[#0a0b0d]">
      <div className="max-w-[1800px] mx-auto">
        <header className="flex items-start justify-between mb-6">
          <div>
            <div className="flex items-center gap-2 text-[11px] font-mono text-slate-600 uppercase tracking-widest mb-2"><span className="w-1.5 h-1.5 bg-teal-700 inline-block" /> Operations / {view === 'list' ? 'Case registry' : view}</div>
            <h1 className="text-xl font-semibold tracking-tight text-slate-100">{view === 'list' ? 'Active investigations' : selectedCase?.number || 'Investigation workspace'}</h1>
            <p className="text-xs text-slate-500 mt-1 font-mono">{view === 'list' ? `${cases.length} cases indexed · last sync 04:32:18 UTC` : selectedCase?.title}</p>
          </div>
          {view === 'list' && <button onClick={() => setView('create')} className="flex items-center gap-2 px-3 py-2 bg-teal-950/40 border border-teal-800/70 text-teal-300 text-xs font-mono hover:bg-teal-900/50 transition-colors"><Plus size={14} /> NEW CASE</button>}
          {view !== 'list' && <button onClick={() => setView('list')} className="text-xs font-mono text-slate-500 hover:text-slate-200">← CASE REGISTRY</button>}
        </header>

        {view === 'list' && <CaseRegistry cases={cases} query={query} setQuery={setQuery} riskFilter={riskFilter} setRiskFilter={setRiskFilter} onOpen={openCase} onCreate={() => setView('create')} />}
        {view === 'create' && <CaseCreate onCreated={(c) => { setSelectedCase(c); setView('detail'); }} />}
        {view === 'detail' && selectedCase && <InvestigationWorkspace item={selectedCase} role={user?.role || 'Analyst'} onNavigate={setView} />}
        {view === 'evidence' && <EvidenceRegistry />}
        {view === 'vasp' && <VaspRegistry />}
        {view === 'audit' && <AuditRegistry />}
        {view === 'report' && <ReportPreview item={selectedCase} />}
        {view === 'sahyog' && <SahyogPanel item={selectedCase} role={user?.role || 'Analyst'} />}
      </div>
    </main>
  );
}

function CaseRegistry({ cases, query, setQuery, riskFilter, setRiskFilter, onOpen, onCreate }: { cases: CaseDetail[]; query: string; setQuery: (v: string) => void; riskFilter: string; setRiskFilter: (v: string) => void; onOpen: (c: CaseDetail) => void; onCreate: () => void }) {
  return <div className="border border-slate-800/80 bg-slate-950/60">
    <div className="flex flex-wrap gap-3 p-3 border-b border-slate-800/80">
      <div className="relative flex-1 min-w-[280px]"><Search size={14} className="absolute left-3 top-2.5 text-slate-600" /><input aria-label="Search cases" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search case number, title, chain..." className="w-full bg-slate-900/70 border border-slate-800 text-xs font-mono text-slate-300 pl-9 pr-3 py-2 outline-none focus:border-teal-800" /></div>
      <select aria-label="Filter by risk" value={riskFilter} onChange={(e) => setRiskFilter(e.target.value)} className="bg-slate-900/70 border border-slate-800 text-xs font-mono text-slate-400 px-3 py-2 outline-none"><option value="all">All risk levels</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select>
      <button className="p-2 border border-slate-800 text-slate-500 hover:text-slate-300"><SlidersHorizontal size={14} /></button>
    </div>
    <div className="grid grid-cols-[105px_minmax(220px,1.5fr)_110px_130px_130px_150px_32px] px-4 py-2 border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-600 font-mono"><span>ID</span><span>Investigation</span><span>Chain</span><span>Risk</span><span>Status</span><span>Last modified</span><span /></div>
    <div className="max-h-[calc(100vh-250px)] overflow-auto">{cases.map((item) => <button key={item.id} onClick={() => onOpen(item)} className="w-full text-left grid grid-cols-[105px_minmax(220px,1.5fr)_110px_130px_130px_150px_32px] items-center px-4 py-3 border-b border-slate-900 hover:bg-slate-900/70 transition-colors group"><span className="font-mono text-[11px] text-teal-600">{item.number}</span><span><span className="block text-xs text-slate-200">{item.title}</span><span className="block text-[10px] text-slate-600 font-mono mt-1">{item.graphState.nodeCount} nodes · {item.graphState.edgeCount} edges</span></span><span className="text-[11px] text-slate-400 font-mono">{item.chain}</span><span><span className={`inline-flex px-2 py-1 text-[10px] font-mono uppercase border ${riskClass[item.riskLevel]}`}>{item.riskLevel}</span></span><span className={`text-[11px] font-mono uppercase ${statusClass[item.status]}`}>{item.status.replace('_', ' ')}</span><span className="text-[11px] text-slate-600 font-mono">{new Date(item.lastModified).toLocaleDateString()}</span><ChevronRight size={14} className="text-slate-700 group-hover:text-teal-600" /></button>)}</div>
  </div>
}

function CaseCreate({ onCreated }: { onCreated: (c: CaseDetail) => void }) {
  const [title, setTitle] = useState(''); const [address, setAddress] = useState(''); const [chain, setChain] = useState<any>('Bitcoin'); const [risk, setRisk] = useState<any>('medium');
  const submit = (e: React.FormEvent) => { e.preventDefault(); const c = store.createCase({ title: title || 'Untitled investigation', chain, riskLevel: risk, seedAddresses: [{ id: 'seed-new', address, chain, riskLevel: risk, tags: ['seed', 'primary'] }] }); onCreated(c); };
  return <form onSubmit={submit} className="max-w-3xl border border-slate-800/80 bg-slate-950/60 p-5 space-y-5"><div className="grid grid-cols-2 gap-4"><Field label="Case title" value={title} onChange={setTitle} placeholder="e.g. Operation Northstar" /><Field label="Seed wallet address" value={address} onChange={setAddress} placeholder="Enter address or transaction hash" /></div><div className="grid grid-cols-3 gap-4"><SelectField label="Network" value={chain} onChange={setChain} options={['Bitcoin','Ethereum','Monero','Ripple','Stablecoin']} /><SelectField label="Initial risk" value={risk} onChange={setRisk} options={['critical','high','medium','low']} /><SelectField label="Assigned analyst" value="Unassigned" onChange={() => {}} options={['Unassigned','Analyst 01','Analyst 02','Analyst 03']} /></div><div className="border-t border-slate-800 pt-4"><div className="text-[10px] font-mono text-slate-600 uppercase tracking-widest mb-3">Initial risk flags</div><div className="flex gap-2 flex-wrap">{['MIXER EXPOSURE','SANCTIONS PROXIMITY','RANSOMWARE TYPOLOGY','CROSS-CHAIN LINK'].map((flag) => <label key={flag} className="flex items-center gap-2 text-[10px] font-mono text-slate-400 border border-slate-800 px-2 py-2"><input type="checkbox" className="accent-teal-700" /> {flag}</label>)}</div></div><div className="flex justify-end gap-2"><button type="button" className="px-3 py-2 text-xs font-mono text-slate-500">CANCEL</button><button type="submit" className="px-4 py-2 bg-teal-950/50 border border-teal-800 text-teal-300 text-xs font-mono">CREATE & TRACE</button></div></form>
}
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (v: string) => void; placeholder: string }) { return <label className="block space-y-2"><span className="text-[10px] font-mono uppercase tracking-wider text-slate-500">{label}</span><input required value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="w-full bg-slate-900/70 border border-slate-800 text-xs font-mono px-3 py-2 text-slate-200 outline-none focus:border-teal-800 placeholder:text-slate-700" /></label> }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[] }) { return <label className="block space-y-2"><span className="text-[10px] font-mono uppercase tracking-wider text-slate-500">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="w-full bg-slate-900/70 border border-slate-800 text-xs font-mono px-3 py-2 text-slate-300 outline-none focus:border-teal-800">{options.map((o) => <option key={o}>{o}</option>)}</select></label> }

function InvestigationWorkspace({ item, role, onNavigate }: { item: CaseDetail; role: string; onNavigate: (v: any) => void }) {
  const [panel, setPanel] = useState<'attribution'|'risk'|'why'|'challenge'|'replay'>('attribution'); const [selectedNode, setSelectedNode] = useState('SEED · 1A1ZP1E');
  return <div className="space-y-4"><div className="flex items-center gap-1 border-b border-slate-800"><Tab active={panel === 'attribution'} onClick={() => setPanel('attribution')}>ATTRIBUTION</Tab><Tab active={panel === 'risk'} onClick={() => setPanel('risk')}>RISK ANALYSIS</Tab><Tab active={panel === 'why'} onClick={() => setPanel('why')}>WHY</Tab><Tab active={panel === 'challenge'} onClick={() => setPanel('challenge')}>CHALLENGE</Tab><Tab active={panel === 'replay'} onClick={() => setPanel('replay')}>REPLAY</Tab><span className="ml-auto flex gap-2"><button onClick={() => onNavigate('evidence')} className="px-2 py-1 text-[10px] font-mono text-slate-500 hover:text-teal-400">EVIDENCE</button><button onClick={() => onNavigate('report')} className="px-2 py-1 text-[10px] font-mono text-slate-500 hover:text-teal-400">REPORT</button>{role === 'Supervisor' && <button onClick={() => onNavigate('sahyog')} className="px-2 py-1 text-[10px] font-mono text-orange-400">SAHYOG</button>}</span></div><div className="grid grid-cols-[250px_minmax(500px,1fr)_310px] gap-3 min-h-[640px]"><aside className="border border-slate-800/80 bg-slate-950/70 p-4 space-y-5"><div><div className="label">CASE SUMMARY</div><div className="mt-2 text-sm text-slate-200">{item.title}</div><div className="mt-2 text-[11px] text-slate-500 font-mono leading-5">Created {new Date(item.createdAt).toLocaleDateString()}<br />Assigned to {item.assignedTo}<br />Network {item.chain}</div></div><div className="border-t border-slate-800 pt-4"><div className="label">SEED ADDRESS</div><div className="mt-2 font-mono text-xs text-teal-500 break-all">{item.seedAddresses[0]?.address || '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'}</div><div className="mt-3 flex gap-2"><span className={`px-2 py-1 text-[10px] border ${riskClass[item.riskLevel]}`}>{item.riskLevel.toUpperCase()} RISK</span></div></div><div className="border-t border-slate-800 pt-4"><div className="label">GRAPH SCOPE</div><div className="grid grid-cols-2 gap-3 mt-3"><Metric label="NODES" value={String(item.graphState.nodeCount)} /><Metric label="EDGES" value={String(item.graphState.edgeCount)} /><Metric label="MAX HOP" value={String(item.graphState.maxHopDepth)} /><Metric label="ASSETS" value="BTC / ETH" /></div></div></aside><GraphView selectedNode={selectedNode} setSelectedNode={setSelectedNode} /><aside className="border border-slate-800/80 bg-slate-950/70 p-4 overflow-auto">{panel === 'attribution' && <AttributionPanel selectedNode={selectedNode} />} {panel === 'risk' && <RiskPanel />} {panel === 'why' && <WhyPanel />} {panel === 'challenge' && <ChallengePanel />} {panel === 'replay' && <ReplayPanel />}</aside></div></div>
}
function Tab({ children, active, onClick }: { children: React.ReactNode; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`px-3 py-2 text-[10px] font-mono tracking-wider border-b-2 ${active ? 'text-teal-400 border-teal-700' : 'text-slate-600 border-transparent hover:text-slate-300'}`}>{children}</button> }
function Metric({ label, value }: { label: string; value: string }) { return <div><div className="text-[9px] text-slate-600 font-mono">{label}</div><div className="text-xs font-mono text-slate-300 mt-1 tabular-nums">{value}</div></div> }
function GraphView({ selectedNode, setSelectedNode }: { selectedNode: string; setSelectedNode: (v: string) => void }) { const nodes = Array.from({length: 18}, (_, i) => ({x: 14 + (i % 6) * 15 + ((i * 7) % 6), y: 15 + Math.floor(i / 6) * 31 + ((i * 11) % 8), risk: ['critical','high','medium','low'][i % 4]})); return <section className="border border-slate-800/80 bg-[#0c0e11] relative overflow-hidden"><div className="absolute top-3 left-3 z-10 flex gap-2"><span className="label bg-[#0c0e11] px-1">TRANSACTION GRAPH</span><span className="text-[10px] font-mono text-teal-700 bg-teal-950/20 px-1">LIVE TRACE</span></div><div className="absolute top-3 right-3 z-10 flex gap-2"><select className="bg-slate-900 border border-slate-800 text-[10px] font-mono text-slate-500 px-2 py-1"><option>HOPS: 5</option></select><select className="bg-slate-900 border border-slate-800 text-[10px] font-mono text-slate-500 px-2 py-1"><option>ALL ASSETS</option></select></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 w-full h-full opacity-60">{nodes.slice(1).map((n,i) => <line key={i} x1={nodes[i].x} y1={nodes[i].y} x2={n.x} y2={n.y} stroke="#33404a" strokeWidth="0.22" />)}</svg><div className="absolute inset-0">{nodes.map((n,i) => <button key={i} onClick={() => setSelectedNode(i === 0 ? 'SEED · 1A1ZP1E' : `ADDR · ${String(i).padStart(2,'0')}F8A2`)} style={{left: `${n.x}%`, top: `${n.y}%`}} className={`absolute -translate-x-1/2 -translate-y-1/2 w-5 h-5 border ${i === 0 ? 'w-8 h-8 border-teal-500 bg-teal-950/80' : n.risk === 'critical' ? 'border-red-700 bg-red-950/50' : n.risk === 'high' ? 'border-orange-700 bg-orange-950/40' : n.risk === 'medium' ? 'border-amber-700 bg-amber-950/40' : 'border-slate-600 bg-slate-900'} rounded-full hover:scale-125 transition-transform`}><span className="sr-only">Select node</span></button>)}</div><div className="absolute bottom-3 left-3 right-3 flex items-center justify-between"><div className="flex gap-3 text-[9px] font-mono text-slate-600"><span><i className="inline-block w-2 h-2 rounded-full bg-red-700 mr-1" />critical</span><span><i className="inline-block w-2 h-2 rounded-full bg-orange-700 mr-1" />high</span><span><i className="inline-block w-2 h-2 rounded-full bg-amber-700 mr-1" />medium</span></div><div className="text-[10px] font-mono text-slate-600">SELECTED: <span className="text-teal-600">{selectedNode}</span></div></div></section> }
function AttributionPanel({ selectedNode }: { selectedNode: string }) { return <div className="space-y-5"><PanelHeading icon={<Crosshair size={14} />} title="ATTRIBUTION" /><div><div className="text-[10px] font-mono text-slate-600">SELECTED NODE</div><div className="font-mono text-xs text-teal-400 mt-1">{selectedNode}</div></div><div className="border border-slate-800 p-3"><div className="flex justify-between items-center"><span className="text-xs text-slate-200">Exchange cluster</span><span className="text-sm font-mono text-teal-400">0.87</span></div><div className="h-1 bg-slate-800 mt-3"><div className="h-full bg-teal-700" style={{width:'87%'}} /></div><div className="mt-3 flex items-center justify-between"><span className="text-[10px] font-mono text-teal-400">CONFIRMED</span><span className="text-[10px] text-slate-600">high confidence</span></div></div><div><div className="label mb-3">CONTRIBUTING SIGNALS</div>{[['Deposit match','0.92'],['Hot-wallet forward','0.81'],['Cluster behavior','0.74'],['External label','0.68']].map(([a,b]) => <div key={a} className="flex items-center justify-between py-2 border-b border-slate-900 text-[11px]"><span className="text-slate-400">{a}</span><span className="font-mono text-slate-300">{b}</span></div>)}</div><button className="w-full flex items-center justify-center gap-2 px-3 py-2 border border-slate-800 text-[10px] font-mono text-slate-500 hover:text-teal-400"><Database size={12} /> VIEW EVIDENCE</button></div> }
function PanelHeading({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="flex items-center gap-2 pb-3 border-b border-slate-800 text-[11px] font-mono text-slate-300 tracking-wider">{icon}<span>{title}</span></div> }
function RiskPanel() { return <div className="space-y-5"><PanelHeading icon={<ShieldAlert size={14} />} title="RISK ASSESSMENT" /><div className="flex items-end justify-between"><div><div className="text-[10px] text-slate-600 font-mono">COMPOSITE SCORE</div><div className="text-4xl font-mono text-red-400 mt-1">8.4<span className="text-sm text-slate-600"> / 10</span></div></div><span className="px-2 py-1 border border-red-900/60 bg-red-950/30 text-red-400 text-[10px] font-mono">CRITICAL</span></div>{[['Mixer contamination','HIGH','red'],['Sanctions proximity','MEDIUM','amber'],['Ransomware typology','HIGH','red'],['Cross-chain exposure','LOW','slate']].map(([a,b,c]) => <div key={a} className="flex items-center justify-between border-b border-slate-900 py-2"><span className="text-[11px] text-slate-400">{a}</span><span className={`text-[10px] font-mono text-${c}-400`}>{b}</span></div>)}<div className="text-[10px] text-slate-600 leading-5">Risk model v2.4 · calibrated against 18,402 known illicit addresses. Last evaluated 04:31:52 UTC.</div></div> }
function WhyPanel() { return <div className="space-y-4"><PanelHeading icon={<Activity size={14} />} title="WHY / EXPLANATION" /><p className="text-[11px] text-slate-400 leading-5">Attribution score is driven by a weighted ensemble of observed transaction patterns and external intelligence.</p>{[['Deposit match','Strong timing and amount correlation','0.92'],['Hot-wallet forward','Funds forwarded within 12m of deposit','0.81'],['Sweep behavior','Consolidation pattern matches cluster','0.74'],['External label','VASP intelligence source · Tier 1','0.68'],['Mixer contamination','2 hops from sanctioned mixer','0.61']].map(([a,b,c]) => <div key={a} className="border border-slate-800 p-3"><div className="flex justify-between text-[11px]"><span className="text-slate-300">{a}</span><span className="font-mono text-teal-400">{c}</span></div><div className="text-[10px] text-slate-600 mt-1">{b}</div><div className="h-0.5 bg-slate-800 mt-2"><div className="h-full bg-teal-800" style={{width:`${Number(c)*100}%`}} /></div></div>)}</div> }
function ChallengePanel() { return <div className="space-y-4"><PanelHeading icon={<RotateCcw size={14} />} title="CHALLENGE / COUNTERFACTUAL" /><div className="border border-orange-900/50 bg-orange-950/10 p-3 text-[11px] text-orange-300 leading-5">Remove one piece of evidence to test hypothesis stability.</div><div className="label">LEAVE-ONE-OUT ANALYSIS</div>{[['Without deposit match','0.42','AMBIGUOUS'],['Without VASP label','0.71','AMBIGUOUS'],['Without mixer link','0.84','CONFIRMED']].map(([a,b,c]) => <div key={a} className="flex items-center justify-between border-b border-slate-900 py-3"><div><div className="text-[11px] text-slate-300">{a}</div><div className="text-[10px] font-mono text-slate-600 mt-1">Hypothesis score</div></div><div className="text-right"><div className="font-mono text-sm text-slate-200">{b}</div><div className="text-[9px] font-mono text-amber-400">{c}</div></div></div>)}<div className="pt-2"><div className="label">NEXT BEST ACTION</div><p className="text-[11px] text-slate-400 mt-2 leading-5">Request exchange KYC disclosure for address cluster 0x7a...f8a2 to resolve remaining ambiguity.</p></div></div> }
function ReplayPanel() { return <div className="space-y-5"><PanelHeading icon={<Activity size={14} />} title="TRACE REPLAY" /><div className="flex items-center justify-between text-[10px] font-mono text-slate-500"><span>STEP 14 / 27</span><span>02:14 elapsed</span></div><input type="range" min="1" max="27" defaultValue="14" className="w-full accent-teal-700" /><div className="border border-slate-800 p-3"><div className="text-[10px] text-teal-500 font-mono">STEP 14 · CLUSTER EXPANSION</div><p className="text-[11px] text-slate-400 mt-2 leading-5">Expanded address cluster based on shared input ownership heuristic. 4 new nodes, 7 transaction edges.</p></div><div className="flex gap-2"><button className="flex-1 py-2 border border-slate-800 text-[10px] font-mono text-slate-500">← PREV</button><button className="flex-1 py-2 border border-teal-800 text-[10px] font-mono text-teal-400">NEXT →</button></div></div> }

function EvidenceRegistry() { const ev = Array.from({length:20},(_,i)=>({id:`EV-${String(i+1).padStart(4,'0')}`,type:['deposit_match','external_label','cluster','mixer_contamination'][i%4],source:['Chainalysis Reactor','Internal heuristic','VASP registry','Block explorer'][i%4],status:i%5===0?'PENDING':'VERIFIED'})); return <Registry title="Evidence register" subtitle="Hash-chained artifacts · immutable record" icon={<FileText size={14} />} headers={['ID','TYPE','SOURCE','CAPTURED','INTEGRITY']} rows={ev.map((e,i)=>[e.id,e.type,e.source,`${String(10+i).padStart(2,'0')}:4${i}:12 UTC`,e.status])} /> }
function VaspRegistry() { const rows = ['Binance','Coinbase','Kraken','Bitstamp','Huobi Global','OKX','Bybit','Gemini','Bitfinex','KuCoin'].map((name,i)=>[`VASP-${String(i+1).padStart(3,'0')}`,name,['US','DE','UK','SG'][i%4],`Tier ${1+(i%3)}`,'FATF / OpenSanctions']); return <Registry title="VASP intelligence" subtitle="Known virtual asset service providers and entity labels" icon={<Database size={14} />} headers={['ID','ENTITY','JURISDICTION','TIER','SOURCE']} rows={rows} /> }
function AuditRegistry() { const rows = Array.from({length:24},(_,i)=>[`AUD-${String(i+1).padStart(5,'0')}`,['CASE_VIEW','TRACE_START','EVIDENCE_EXPORT','LABEL_UPDATE'][i%4],['analyst.jchen','s.investigator','supervisor.rpatel'][i%3],`2026-09-27 0${i%9}:4${i}:12`,'CHAIN VALID']); return <Registry title="Audit log" subtitle="Read-only · tamper-evident activity stream" icon={<Activity size={14} />} headers={['EVENT','ACTION','ACTOR','TIMESTAMP','INTEGRITY']} rows={rows} /> }
function Registry({title,subtitle,icon,headers,rows}:{title:string;subtitle:string;icon:React.ReactNode;headers:string[];rows:string[][]}) { return <div className="border border-slate-800/80 bg-slate-950/60"><div className="p-4 border-b border-slate-800 flex items-center gap-3">{icon}<div><h2 className="text-sm text-slate-200">{title}</h2><p className="text-[10px] text-slate-600 font-mono mt-1">{subtitle}</p></div><span className="ml-auto text-[10px] font-mono text-teal-700">{rows.length} RECORDS</span></div><div className="overflow-auto"><div className="grid grid-cols-5 px-4 py-2 border-b border-slate-800 text-[10px] font-mono text-slate-600">{headers.map(h=><span key={h}>{h}</span>)}</div>{rows.map((row,i)=><div key={i} className="grid grid-cols-5 px-4 py-3 border-b border-slate-900 hover:bg-slate-900/60 text-[11px] font-mono"><span className="text-teal-600">{row[0]}</span>{row.slice(1).map((cell,j)=><span key={j} className={cell.includes('VALID')||cell.includes('VERIFIED')?'text-teal-500':cell.includes('PENDING')?'text-amber-400':'text-slate-400'}>{cell}</span>)}</div>)}</div></div> }
function ReportPreview({item}:{item:CaseDetail|null}) { return <div className="grid grid-cols-[1fr_300px] gap-4"><div className="border border-slate-800 bg-slate-100 text-slate-900 min-h-[700px] p-10"><div className="flex justify-between border-b border-slate-300 pb-5"><div><div className="text-xs font-mono font-bold">VAULT-X / INTELLIGENCE REPORT</div><h2 className="text-2xl font-semibold mt-6">{item?.title || 'Investigation report'}</h2><p className="text-xs text-slate-500 mt-2">Case {item?.number} · CLASSIFICATION: LAW ENFORCEMENT SENSITIVE</p></div><div className="text-right text-[10px] font-mono text-slate-500">GENERATED<br/>2026-09-27</div></div><h3 className="font-semibold text-sm mt-8">Executive summary</h3><p className="text-xs leading-6 mt-3 text-slate-600">This report documents the forensic analysis of identified blockchain transactions, attribution hypotheses, and supporting evidence. Findings are presented with epistemic labels and confidence scores.</p><h3 className="font-semibold text-sm mt-8">Methodology</h3><p className="text-xs leading-6 mt-3 text-slate-600">Analysis applied normalized transaction tracing, cluster heuristics, VASP intelligence, and counterfactual validation across {item?.graphState.nodeCount || 64} nodes and {item?.graphState.edgeCount || 138} edges.</p><div className="mt-12 p-4 border border-slate-300 font-mono text-[10px] text-slate-500">INTEGRITY BLOCK<br/><span className="text-slate-800">SHA-256: 7f8e9d2a6b5c4e3d...</span><br/>Manifest: run-2026-0927-0042 · Chain valid</div></div><div className="border border-slate-800 bg-slate-950/60 p-4 h-fit space-y-3"><div className="label">REPORT ACTIONS</div><button className="w-full flex items-center justify-center gap-2 py-2 border border-teal-800 text-teal-400 text-[10px] font-mono"><Download size={12}/> DOWNLOAD PDF</button><button className="w-full flex items-center justify-center gap-2 py-2 border border-slate-800 text-slate-400 text-[10px] font-mono"><Download size={12}/> EXPORT JSON</button></div></div> }
function SahyogPanel({item,role}:{item:CaseDetail|null;role:string}) { const [status,setStatus]=useState('DRAFT'); return <div className="max-w-4xl border border-slate-800 bg-slate-950/60"><div className="p-4 border-b border-slate-800 flex justify-between"><div><h2 className="text-sm text-slate-200">SAHYOG referral preparation</h2><p className="text-[10px] text-slate-600 font-mono mt-1">External referral adapter · payload preview</p></div><span className="text-[10px] font-mono text-orange-400">{status}</span></div><div className="p-5 grid grid-cols-2 gap-5"><div className="space-y-4"><div className="label">REFERRAL SUBJECT</div><Field label="Case reference" value={item?.number || ''} onChange={()=>{}} placeholder="" /><Field label="Primary entity" value={item?.seedAddresses[0]?.address || ''} onChange={()=>{}} placeholder="" /></div><div className="space-y-4"><div className="label">PAYLOAD SUMMARY</div><div className="border border-slate-800 p-3 font-mono text-[10px] text-slate-500 leading-6">{`{`}<br/>&nbsp;&nbsp;"protocol": "SAHYOG/1.0",<br/>&nbsp;&nbsp;"case": "{item?.number}",<br/>&nbsp;&nbsp;"classification": "LES",<br/>&nbsp;&nbsp;"evidence_count": 18,<br/>&nbsp;&nbsp;"integrity": "chain_valid"<br/>{`}`}</div></div></div><div className="p-5 border-t border-slate-800 flex justify-end">{role === 'Supervisor' ? <button onClick={()=>setStatus('PENDING APPROVAL')} className="flex items-center gap-2 px-4 py-2 bg-orange-950/30 border border-orange-800 text-orange-300 text-[10px] font-mono"><Send size={12}/> SUBMIT FOR APPROVAL</button> : <span className="text-[10px] text-slate-600 font-mono">Supervisor approval required to submit</span>}</div></div> }
export { InvestigationWorkspace };

// Keep a small, explicit data contract reference close to UI surfaces.
export type EvidenceRow = Pick<Evidence, 'id' | 'type' | 'source' | 'verified'>;
export type HypothesisRow = Pick<AttributionHypothesis, 'id' | 'hypothesis' | 'score' | 'epistemicLabel'>;

// shared utility used by dense panels
export function formatAmount(amount: number) { return amount.toLocaleString('en-US', { maximumFractionDigits: 6 }); }

// Keep these symbols discoverable for future API wiring without adding visual noise.
export const panelActions = { close: X, approve: CheckCircle2, export: Download };

// Avoid unused-import diagnostics in strict builds while keeping the action set explicit.
void MoreHorizontal;
void ShieldAlert;
void CheckCircle2;
void Download;
void Send;
void X;
void FileText;
void Database;
void Activity;
void Search;
void SlidersHorizontal;
void ChevronRight;
void Plus;
void Crosshair;
void RotateCcw;
