"""Data-requisition notices to VASPs, generated from the OSINT targets of a run."""
from __future__ import annotations

import hashlib
import json
import os
import re
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from app.case_context import CaseContext
from app.pdf import AMBER, GREY, MARGIN_X, NAVY, PdfDocument, text_width

CONTACTS_FILE = Path(__file__).resolve().parent.parent / "data" / "vasp_contacts.json"
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

LEGAL_BASIS = "Section 94 of the Bharatiya Nagarik Suraksha Sanhita, 2023 (BNSS)"

DEFAULT_RECORDS = [
    "KYC records of the account holder(s) linked to the deposit address: full name, identity documents, address and date of birth.",
    "Registered mobile number(s) and e-mail address(es), with dates of registration and change.",
    "Login and session history with IP addresses, timestamps and device identifiers.",
    "Complete deposit and withdrawal history, including crypto addresses and linked bank accounts or payment instruments.",
    "Details of any other accounts linked by KYC, device, IP address or payment instrument.",
    "Current balance and holdings, and the status of any freeze or restriction on the account.",
]


def load_contacts() -> dict[str, dict[str, Any]]:
    path = Path(os.getenv("VASP_CONTACTS_FILE") or CONTACTS_FILE)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return {k.lower(): v for k, v in data.items() if not k.startswith("_") and isinstance(v, dict)}


def recipient_for(vasp: str) -> dict[str, Any]:
    contacts = load_contacts()
    key = vasp.lower()
    entry = contacts.get(key) or next((v for k, v in contacts.items() if k in key or key in k), None) or {}
    return {
        "email": entry.get("lawEnforcementEmail"),
        "portal": entry.get("lawEnforcementPortal"),
        "verified": bool(entry.get("verified")),
        "source": "vasp-contacts directory" if entry else None,
    }


def drafts(ctx: CaseContext) -> list[dict[str, Any]]:
    out = []
    for t in ctx.osint["targets"]:
        out.append({
            "targetId": t["id"],
            "vasp": t["vasp"],
            "targetAddress": t["targetAddress"],
            "chain": t["chain"],
            "attributionScore": t["attributionScore"],
            "band": t["band"],
            "priority": t["priority"],
            "website": t["profile"]["website"],
            "recipient": recipient_for(t["vasp"]),
            "channels": [c for c in t["channels"] if c["status"] == "FOUND"],
            "inflow": t["inflow"],
            "suggestedRecords": DEFAULT_RECORDS,
            "legalBasis": LEGAL_BASIS,
            "calibrated": False,
        })
    return out


def _find_target(ctx: CaseContext, target_id: str, address: str | None = None) -> dict[str, Any] | None:
    return next((t for t in ctx.osint["targets"] if t["id"] == target_id and (not address or t["targetAddress"] == address)), None)


def _iso_date(ts: Any) -> str:
    try:
        return datetime.fromtimestamp(int(ts), tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    except (TypeError, ValueError, OSError):
        return "-"


def notice_number(ctx: CaseContext, vasp: str, when: datetime) -> str:
    slug = re.sub(r"[^A-Z0-9]", "", vasp.upper())[:8] or "VASP"
    return f"VX/{ctx.case.number}/{slug}/{when:%Y%m%d}/{uuid.uuid4().hex[:4].upper()}"


def render_notice(ctx: CaseContext, target: dict[str, Any], officer: dict[str, str], recipient_email: str, deadline_days: int, records: list[str], number: str, when: datetime) -> bytes:
    unit = officer.get("unit") or "Cyber Crime Investigation Unit"
    doc = PdfDocument(
        title=f"Notice {number}",
        header_left="CONFIDENTIAL  |  LAW ENFORCEMENT REQUEST",
        header_right=f"Ref. {number}",
        footer_note=f"Generated by VAULT-X from case {ctx.case.number}. {ctx.banner}. Attribution scores are UNCALIBRATED.",
    )
    deadline = when + timedelta(days=deadline_days)
    incoming = [tx for tx in ctx.transactions if tx.get("to") == target["targetAddress"] and tx.get("from") != tx.get("to")]

    doc.text(MARGIN_X, doc.y - 12, unit.upper(), "bold", 12, NAVY)
    doc.y -= 30
    title = "NOTICE UNDER SECTION 94, BNSS 2023"
    doc.text((595.28 - text_width(title, "bold", 14)) / 2, doc.y - 14, title, "bold", 14, (0, 0, 0))
    doc.y -= 20
    sub = "Requisition for production of records and preservation of data"
    doc.text((595.28 - text_width(sub, "italic", 10)) / 2, doc.y - 10, sub, "italic", 10, GREY)
    doc.y -= 26

    doc.kv([
        ("Reference No.", number),
        ("Date", when.strftime("%d %B %Y")),
        ("Case reference", f"{ctx.case.number} ({ctx.case.title})"),
        ("To", f"The Nodal Officer / Law Enforcement Response Team, {target['vasp']}"),
        ("Recipient", recipient_email),
        ("Respond by", deadline.strftime("%d %B %Y") + f" ({deadline_days} days)"),
    ], key_width=120)

    doc.paragraph(f"Subject: Production of account records linked to the {target['chain'] or 'blockchain'} address {target['targetAddress']} in connection with {ctx.case.number}.", 10, "bold")
    doc.paragraph(
        f"Whereas an investigation is in progress in case {ctx.case.number}, and whereas the undersigned has reason to believe that the records "
        f"listed below, held by {target['vasp']}, are necessary and desirable for the purposes of that investigation, you are hereby required "
        f"under {LEGAL_BASIS} to produce the said records to the undersigned on or before {deadline.strftime('%d %B %Y')}."
    )

    doc.heading("1. Facts established from the blockchain (Observed)", 2)
    doc.paragraph(f"The following transfers into the address {target['targetAddress']} were recorded on-chain and are reproduced from the case evidence register.", 9.5)
    if incoming:
        doc.table(["Transaction hash", "Date (UTC)", "Amount", "From"],
                  [[tx.get("txHash") or tx.get("id"), _iso_date(tx.get("timestamp")), f"{tx.get('amount')} {tx.get('asset', '')}", tx.get("from")] for tx in incoming[:25]],
                  [3.2, 1.4, 1.1, 2.6], size=7.5, mono_cols=(0, 3))
        if len(incoming) > 25:
            doc.paragraph(f"{len(incoming) - 25} further transfers are listed in the case evidence register.", 8.5, "italic", GREY)
    else:
        doc.paragraph("No individual transfer rows are held for this address in the run; see the attached case evidence register.", 9, "italic", GREY)

    doc.heading("2. Basis for attributing the address to your platform (Attributed)", 2)
    doc.bullets([
        f"Attribution to {target['vasp']}: score {target['attributionScore']:.2f} ({target['band']}). This score is UNCALIBRATED and indicates investigative priority, not proof of ownership.",
        f"Epistemic status: {target['epistemicLabel']}. Supporting evidence references: {', '.join(target['supporting']) or 'known-exchange registry match'}.",
        "You are requested to confirm or deny that the address is a deposit address controlled by your platform.",
    ], 9.5)

    doc.heading("3. Records required", 2)
    doc.bullets([f"({i}) {r}" for i, r in enumerate(records, start=1)], 9.5)

    doc.heading("4. Preservation and confidentiality", 2)
    doc.bullets([
        "Preserve all records relating to the account(s) and address above, and do not delete or alter them, pending further legal process.",
        "Do not disclose this notice or its contents to the account holder or any third party, as disclosure may prejudice the investigation.",
        "Where lawful, restrict withdrawals from the account(s) and inform the undersigned of any action taken.",
    ], 9.5)

    doc.heading("5. Mode of response", 2)
    doc.paragraph(
        f"Send the records in electronic form, with a certificate of authenticity for electronic records, by reply to {officer.get('email') or 'the undersigned'} "
        "or through the SAHYOG portal, quoting the reference number above.", 9.5)

    doc.signature_block([
        officer.get("name") or "Investigating Officer",
        officer.get("rank") or "",
        unit,
        f"E-mail: {officer.get('email') or '-'}",
        f"Phone: {officer.get('phone') or '-'}",
    ], "Signature and seal of the Investigating Officer")

    doc.new_page()
    doc.heading("Annexure A: Open-source intelligence on the addressee", 1)
    doc.paragraph("Public channels of the addressee platform, collected for identification and routing only. These are organisation-level profiles from a curated registry (tier C) and are not profiles of the account holder.", 9)
    rows = [[c["platform"], c["handle"] or "-", c["url"] or c["note"], c["status"], c["epistemicLabel"]] for c in target["channels"]]
    doc.table(["Platform", "Handle", "Link / note", "Status", "Label"], rows, [1.2, 1.3, 3.2, 1.1, 1.1], size=7.5)
    doc.heading("Public search pivots for the address", 2)
    for p in target["pivots"]:
        doc.ensure(12)
        doc.text(MARGIN_X, doc.y - 9, f"{p['name']}:", "bold", 8)
        doc.text(MARGIN_X + 120, doc.y - 9, p["url"][:95], "mono", 7, (0.05, 0.3, 0.7))
        doc.link(MARGIN_X + 120, doc.y - 11, 380, 11, p["url"])
        doc.y -= 12
    doc.space(8)
    doc.heading("Integrity references", 2)
    doc.kv([
        ("Evidence chain head", ctx.chain.get("headHash") or "no evidence records"),
        ("Evidence chain status", "VALID" if ctx.chain.get("valid") else f"BROKEN at {ctx.chain.get('firstBrokenLink')}"),
        ("Investigation run", ctx.run.id),
        ("Data basis", ctx.banner),
    ], key_width=140, size=8.5)
    doc.notice_box("This notice was generated from a template by VAULT-X. The legal wording must be reviewed by the issuing unit before dispatch. "
                   "Attribution scores are UNCALIBRATED. Account-holder identity has not been inferred and is requested from the addressee.", AMBER)
    return doc.to_bytes(when)


def create_notice(ctx: CaseContext, body: dict[str, Any]) -> dict[str, Any]:
    target = _find_target(ctx, str(body.get("targetId") or ""), body.get("targetAddress"))
    if target is None:
        raise ValueError("Unknown target for this run. Load the notice drafts again.")
    recipient = str(body.get("recipientEmail") or "").strip()
    if not EMAIL_RE.match(recipient):
        raise ValueError("A valid recipient e-mail address is required.")
    officer = {k: str(v).strip() for k, v in (body.get("officer") or {}).items() if v}
    deadline_days = max(1, min(90, int(body.get("deadlineDays") or 7)))
    records = [str(r) for r in (body.get("records") or DEFAULT_RECORDS) if str(r).strip()]
    when = datetime.now(timezone.utc).replace(microsecond=0)
    number = notice_number(ctx, target["vasp"], when)
    pdf = render_notice(ctx, target, officer, recipient, deadline_days, records, number, when)
    return {
        "pdf": pdf,
        "sha256": hashlib.sha256(pdf).hexdigest(),
        "title": f"Notice to {target['vasp']} ({number})",
        "meta": {
            "noticeNumber": number,
            "vasp": target["vasp"],
            "targetId": target["id"],
            "targetAddress": target["targetAddress"],
            "recipientEmail": recipient,
            "officer": officer,
            "deadline": (when + timedelta(days=deadline_days)).date().isoformat(),
            "records": records,
            "legalBasis": LEGAL_BASIS,
            "banner": ctx.banner,
            "deliveries": [],
            "calibrated": False,
        },
    }


def email_text(meta: dict[str, Any], case_number: str) -> tuple[str, str]:
    subject = f"[{meta['noticeNumber']}] Notice under Section 94 BNSS: records for case {case_number}"
    officer = meta.get("officer") or {}
    body = (
        f"To the Nodal Officer / Law Enforcement Response Team, {meta['vasp']}\n\n"
        f"Please find attached notice {meta['noticeNumber']} issued under {meta['legalBasis']} in connection with case {case_number}, "
        f"concerning the address {meta['targetAddress']}.\n\n"
        f"Kindly produce the records listed in the notice by {meta['deadline']} and preserve all related data. "
        "Please do not disclose this request to the account holder.\n\n"
        f"{officer.get('name') or 'Investigating Officer'}\n{officer.get('rank') or ''}\n{officer.get('unit') or ''}\n{officer.get('email') or ''}\n"
    )
    return subject, body
