'use client';
import { useEffect, useMemo, useState } from 'react';
import CytoscapeComponent from 'react-cytoscapejs';
import { api, ApiOfflineError, Attribution, CaseSummary, GraphResponse } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
type View = 'list'|'create'|'detail'|'evidence'|'vasp'|'audit'|'report'|'sahyog';
const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="border border-slate-800 bg-slate-950/70 p-4"><h2 className="mb-3 font-mono text-xs tracking-wider text-teal-400">{title}</h2>{children}</section>;
export function CaseListView({ initialView='list' }: { initialView?: View }) {
 const [view,setView]=useState<View>(initialView),[cases,setCases]=useState<CaseSummary[]>([]),[runId,setRunId]=useState<string>(),[offline,setOffline]=useState(false);
 const load=()=>api.cases().then(setCases).catch(error=>setOffline(error instanceof ApiOfflineError)); useEffect(load,[]); useEffect(()=>{const listener=(event:Event)=>setView((event as CustomEvent<View>).detail);window.addEventListener('vault-x:navigate',listener);return()=>window.removeEventListener('vault-x:navigate',listener)},[]);
 const open=async(item:CaseSummary)=>{try{setRunId((await api.startInvestigation(item.id)).id);setView('detail')}catch(error){setOffline(error instanceof ApiOfflineError)}};
 return <main className="min-h-screen bg-[#0a0b0d] p-6 text-slate-200"><div className="mb-4 border border-teal-900 bg-teal-950/30 p-2 font-mono text-xs text-teal-300">CASE REPLAY — BITFINEX 2016 PUBLIC DATASET</div>{offline&&<div className="mb-4 border border-amber-800 bg-amber-950/20 p-3 font-mono text-xs text-amber-300">API OFFLINE — live case data is unavailable; no mock data is displayed.</div>}
 {view==='list'&&<Panel title="CASE REGISTRY"><button className="mb-3 border border-teal-800 px-3 py-2 font-mono text-xs text-teal-300" onClick={()=>setView('create')}>CREATE CASE</button>{cases.map(item=><button className="block w-full border-t border-slate-800 py-3 text-left text-sm hover:text-teal-300" key={item.id} onClick={()=>open(item)}><span className="font-mono text-teal-500">{item.number}</span> · {item.title}</button>)}</Panel>}
 {view==='create'&&<Create onCreated={load}/>} {view==='detail'&&<Graph runId={runId}/>} {view==='evidence'&&<Evidence/>} {view==='vasp'&&<Vasps/>} {view==='audit'&&<Audit/>} {view==='report'&&<Reports runId={runId}/>} {view==='sahyog'&&<Sahyog attributionId="Xzzx.biz"/>}</main>;
}
function Create({onCreated}:{onCreated:()=>void}){const [title,setTitle]=useState('');return <Panel title="CREATE CASE"><input className="border border-slate-700 bg-slate-900 p-2 text-sm" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Case title"/><button className="ml-2 border border-teal-800 p-2 text-xs" onClick={async()=>{await api.createCase(`CASE-${Date.now()}`,title);onCreated()}}>SAVE</button></Panel>}
function Graph({runId}:{runId?:string}){const [graph,setGraph]=useState<GraphResponse>({nodes:[],edges:[],banner:''}),[items,setItems]=useState<Attribution[]>([]),[selected,setSelected]=useState<Record<string,unknown>|null>(null),[tab,setTab]=useState<'attribution'|'challenge'|'replay'>('attribution'),[min,setMin]=useState('0'),[label,setLabel]=useState(''),[drawer,setDrawer]=useState(false);useEffect(()=>{if(runId){api.graph(runId).then(setGraph);api.attribution(runId).then(setItems)}},[runId]);const elements=useMemo(()=>[...graph.nodes.filter(n=>!label||n.label.includes(label)).map(n=>({data:{id:n.id,label:n.label,...n.data},classes:n.id.startsWith('virtual:')?'virtual aggregate':''})),...graph.edges.filter(e=>Number((e.data?.amount as number)||0)>=Number(min)).map(e=>({data:{id:e.id,source:e.source,target:e.target,...e.data},classes:e.epistemicLabel==='CASE_ASSERTED'?'asserted':''}))],[graph,label,min]);return <div className="grid gap-4 lg:grid-cols-[1fr_320px]"><Panel title="GRAPH EXPLORER"><div className="mb-2 flex gap-2"><input aria-label="Minimum BTC" className="w-24 bg-slate-900 p-1 text-xs" value={min} onChange={e=>setMin(e.target.value)} placeholder="min BTC"/><input aria-label="Label filter" className="bg-slate-900 p-1 text-xs" value={label} onChange={e=>setLabel(e.target.value)} placeholder="label"/><span className="font-mono text-[10px] text-slate-500">cose / concentric · virtual / asserted styling</span></div><CytoscapeComponent elements={elements} layout={{name:'cose'} as never} style={{height:'460px',width:'100%'}} stylesheet={[{selector:'node',style:{label:'data(label)',color:'#cbd5e1','font-size':8}},{selector:'node.virtual',style:{'background-color':'#0f766e',shape:'diamond'}},{selector:'node.aggregate',style:{'border-width':2,'border-color':'#5eead4'}},{selector:'edge.asserted',style:{'line-style':'dashed','line-color':'#2dd4bf'}}]} cy={cy=>cy.on('tap','node',event=>setSelected(event.target.data()) )}/></Panel><Panel title="INVESTIGATION"><div className="mb-3 text-xs text-slate-400">Selected: {String(selected?.label||'none')} · aggregate nodes are expandable.</div><div className="flex gap-2 border-b border-slate-800 pb-2">{(['attribution','challenge','replay'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className="font-mono text-[10px] text-teal-400">{t.toUpperCase()}</button>)}</div>{tab==='attribution'&&<AttributionPanel items={items} drawer={drawer} setDrawer={setDrawer}/>} {tab==='challenge'&&<Challenge items={items}/>} {tab==='replay'&&<Replay/>}</Panel></div>}
function AttributionPanel({items,drawer,setDrawer}:{items:Attribution[];drawer:boolean;setDrawer:(value:boolean)=>void}){const top=items[0];return <div className="space-y-3 pt-3"><span className="border border-amber-800 px-2 py-1 font-mono text-[10px] text-amber-300">UNCALIBRATED</span>{top?<><p className="text-sm">{top.hypothesis} · {Number(top.score).toFixed(2)} · {top.band}</p><p className="text-xs text-slate-500">{top.epistemicLabel==='NO_ATTRIBUTION'?'ABSTAINED: no attribution.':'Single tier-C source; not confirmed.'}</p><button className="border border-teal-800 p-2 text-[10px]" onClick={()=>setDrawer(!drawer)}>WHY THIS VASP?</button>{drawer&&<div className="border border-slate-800 p-2 text-xs">{top.supporting.map(id=><button key={id} className="block text-teal-400">{id} · OBSERVED / ATTRIBUTED</button>)}</div>}</>:<p className="text-xs text-slate-500">No attribution data.</p>}</div>}
function Challenge({items}:{items:Attribution[]}){const top=items[0];return <div className="space-y-3 pt-3 text-xs"><p>Alternatives: {items.slice(1).map(x=>x.hypothesis).join(', ')||'NO_ATTRIBUTION'}</p><p>Contradicting evidence: {top?.contradicting.join(', ')||'none'}</p><p>Evidence gaps: {top?.nextActions.join(' ')||'Second independent source required.'}</p><p className="text-amber-300">Sensitivity: removing the tier-C label changes the conclusion to NO_ATTRIBUTION.</p></div>}
function Replay(){const [step,setStep]=useState(1);return <div className="pt-3 text-xs"><input className="w-full accent-teal-600" type="range" min="1" max="3" value={step} onChange={e=>setStep(Number(e.target.value))}/><p className="mt-2">Step {step}: SNAPSHOT / CASE REPLAY trace event.</p></div>}
function Evidence(){const [rows,setRows]=useState<Array<Record<string,unknown>>>([]),[result,setResult]=useState('');useEffect(()=>{api.evidence().then(setRows)},[]);return <Panel title="EVIDENCE REGISTER">{rows.map(row=><div key={String(row.id)} className="border-t border-slate-800 py-2 text-xs"><button className="text-teal-400" onClick={async()=>{const r=await api.verifyEvidence(String(row.id));setResult(r.valid?'OK':`broken-at-${r.firstBrokenLink}`)}}>VERIFY CHAIN</button> · {String(row.id)} · {String(row.type)}</div>)}<p className="mt-2 font-mono text-teal-300">{result}</p></Panel>}
function Vasps(){const [items,setItems]=useState<Array<Record<string,unknown>>>([]);useEffect(()=>{api.vasps().then(result=>setItems(result.items))},[]);return <Panel title="VASP INTELLIGENCE">{items.map(x=><p key={String(x.name)} className="text-xs">{String(x.name)} · source: {String(x.sourceTier)} · tier C / unverified</p>)}</Panel>}
function Audit(){const [items,setItems]=useState<Array<Record<string,unknown>>>([]);useEffect(()=>{api.audit().then(setItems)},[]);return <Panel title="AUDIT LOG">{items.map(x=><p key={String(x.id)} className="text-xs">{String(x.who)} · {String(x.what)} · {String(x.resource)}</p>)}</Panel>}
function Reports({runId}:{runId?:string}){const [items,setItems]=useState<Array<Record<string,unknown>>>([]);return <Panel title="REPORTS"><button className="border border-teal-800 p-2 text-xs" onClick={()=>runId&&api.reports(runId).then(setItems)}>GENERATE / LOAD JSON</button><button className="ml-2 border border-slate-700 p-2 text-xs" onClick={()=>window.open('http://localhost:8000/api/v1/reports/REPORT-CYBER-2026-001/html')}>OPEN HTML</button><button className="ml-2 border border-slate-700 p-2 text-xs" onClick={()=>{const blob=new Blob([JSON.stringify(items)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vaultx-report.json';a.click()}}>DOWNLOAD JSON</button></Panel>}
function Sahyog({attributionId}:{attributionId:string}){const {user}=useAuth();const [reply,setReply]=useState<Record<string,unknown>|null>(null);return <Panel title="SAHYOG: MOCK"><p className="mb-3 text-xs text-amber-300">MOCK — not submitted to any government system.</p><button className="border border-teal-800 p-2 text-xs" onClick={()=>api.prepareSahyog(attributionId).then(setReply)}>PREPARE MOCK</button>{user?.role==='Supervisor'&&<button className="ml-2 border border-amber-800 p-2 text-xs" onClick={()=>api.approveSahyog(attributionId).then(setReply)}>SUPERVISOR APPROVE</button>}<pre className="mt-3 text-[10px] text-slate-500">{reply&&JSON.stringify(reply,null,2)}</pre></Panel>}
